modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
[[mods]]
modId="hunted"
version="0.4"
displayName="Hunted"
logoFile="hunted_logo.png"
authors="nonamecrackers2"
credits="TheFrostySoul, TCBlizz707, Funglscrun"
description='''
Official mod for Hunted
'''

[[dependencies.hunted]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hunted]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
